### ISSUE TITLE
模型注册问题

### ISSUE THREAD

**Issue by Lee-inso** [ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing#22]
KeyError: 'swin is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    return build_from_cfg(cfg, registry, default_args)  File "/media/user/volume/PycharmProjects/ViTAE-Transformer-Remote-Sensing-main/Semantic Segmentation/tools/train.py", line 234, in <module>

  File "/home/user/.conda/envs/pytorch/lib/python3.10/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'swin is not in the models registry'

求问如何debug

**Comment by Lee-inso** [comment]
python setup.py install 了，但是可修改的mmcv是什么意思？
mmcv我是按照官方指导min 安装的full

**Comment by DotWang** [comment]
@Lee-inso 说的应该是可修改的mmseg

`Case a: If you develop and run mmseg directly, install it from source:`

https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/get_started.md#installation

**Comment by Lee-inso** [comment]
3q
问一下，拿rsp做下游任务，泛化性还是比较差，有没有什么比较好的trick，或者比较好的增强泛化性的研究方向，感谢指教🙏

**Comment by DotWang** [comment]
@Lee-inso rsp是监督预训练的，监督不如无监督效果好。你可以试试我们的无监督预训练遥感大模型：https://github.com/ViTAE-Transformer/Remote-Sensing-RVSA

**Comment by Lee-inso** [comment]
> @Lee-inso rsp是监督预训练的，监督不如无监督效果好。你可以试试我们的无监督预训练遥感大模型：https://github.com/ViTAE-Transformer/Remote-Sensing-RVSA
万分感谢！思想上是mae的小改进版本么？
